# Generated by Django 3.2.9 on 2024-03-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=100)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_covered', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resting_period', models.IntegerField()),
                ('step_counts', models.IntegerField()),
                ('stress_levels', models.CharField(max_length=100)),
                ('hydration_status', models.CharField(max_length=100)),
                ('heart_rate', models.IntegerField()),
                ('calorie_expenditure', models.IntegerField()),
                ('sleep_quality', models.CharField(max_length=100)),
                ('training_advice', models.TextField(blank=True, null=True)),
                ('health_advice', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.player')),
            ],
        ),
    ]
